//! `cargo xtask regen-proto` — rewrite the checked-in lightwalletd bindings.
//!
//! - Sole reason this crate exists: keep `protoc` out of the published build graph
//! - Drift = `git diff --exit-code src/proto/generated.rs` after a regen (CI does exactly that)

use std::error::Error;
use std::path::Path;
use std::{fs, process::ExitCode};

const PROTOS: [&str; 2] = ["proto/compact_formats.proto", "proto/service.proto"];
const PACKAGE: &str = "cash.z.wallet.sdk.rpc.rs";
const CHECKED_IN: &str = "src/proto/generated.rs";

const HEADER: &str = "\
// @generated by `cargo xtask regen-proto` from proto/*.proto — DO NOT EDIT.
";

fn main() -> ExitCode {
    if let Err(e) = regen() {
        eprintln!("xtask: {e}");
        return ExitCode::FAILURE;
    }
    println!("wrote {CHECKED_IN}");
    ExitCode::SUCCESS
}

// Client only (ztest drives pod-hosted indexers, never serves the API); both protos share
// one package, so a single compile emits one flat module.
fn regen() -> Result<(), Box<dyn Error>> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().expect("xtask/ has a parent");
    let out = root.join("target/xtask-proto");
    fs::create_dir_all(&out)?;
    let protos: Vec<_> = PROTOS.iter().map(|p| root.join(p)).collect();
    tonic_prost_build::configure()
        .build_server(false)
        .out_dir(&out)
        .compile_protos(&protos, &[root.join("proto")])?;
    let generated = fs::read_to_string(out.join(PACKAGE))?;
    Ok(fs::write(root.join(CHECKED_IN), format!("{HEADER}{generated}"))?)
}
