//! `cargo xtask regen-proto` — rewrite the checked-in lightwalletd bindings.
//! `cargo xtask release-gate` — cargo-release `pre-release-hook`; fails unless HEAD = upstream tip.
//!
//! - Sole reason this crate exists: keep `protoc` out of the published build graph
//! - Drift = `git diff --exit-code src/proto/generated.rs` after a regen (CI does exactly that)

use std::error::Error;
use std::path::Path;
use std::process::Command;
use std::{env, fs, process::ExitCode};

const PROTOS: [&str; 2] = ["proto/compact_formats.proto", "proto/service.proto"];
const PACKAGE: &str = "cash.z.wallet.sdk.rpc.rs";
const CHECKED_IN: &str = "src/proto/generated.rs";

const HEADER: &str = "\
// @generated by `cargo xtask regen-proto` from proto/*.proto — DO NOT EDIT.
";

fn main() -> ExitCode {
    let result = match env::args().nth(1).as_deref() {
        Some("regen-proto") => regen().map(|()| println!("wrote {CHECKED_IN}")),
        Some("release-gate") => release_gate(),
        _ => Err("usage: cargo xtask <regen-proto | release-gate>".into()),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("xtask: {e}");
            ExitCode::FAILURE
        }
    }
}

// Client only (ztest drives pod-hosted indexers, never serves the API); both protos share
// one package, so a single compile emits one flat module.
fn regen() -> Result<(), Box<dyn Error>> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().expect("xtask/ has a parent");
    let out = root.join("target/xtask-proto");
    fs::create_dir_all(&out)?;
    let protos: Vec<_> = PROTOS.iter().map(|p| root.join(p)).collect();
    tonic_prost_build::configure()
        .build_server(false)
        .out_dir(&out)
        .compile_protos(&protos, &[root.join("proto")])?;
    let generated = fs::read_to_string(out.join(PACKAGE))?;
    Ok(fs::write(root.join(CHECKED_IN), format!("{HEADER}{generated}"))?)
}

// - Fetch only (worktree + local branch untouched)
// - Branch gate lives in release.toml `allow-branch`, not here
fn release_gate() -> Result<(), Box<dyn Error>> {
    git(&["fetch", "--quiet"])?;
    let upstream = git(&["rev-parse", "--abbrev-ref", "@{upstream}"])?;
    let (head, tip) = (git(&["rev-parse", "HEAD"])?, git(&["rev-parse", "@{upstream}"])?);
    if head != tip {
        return Err(
            format!("HEAD {head:.9} != {upstream} {tip:.9}; sync with {upstream} first").into()
        );
    }
    Ok(())
}

fn git(args: &[&str]) -> Result<String, Box<dyn Error>> {
    let out = Command::new("git").args(args).output()?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        return Err(format!("git {}: {}", args.join(" "), stderr.trim()).into());
    }
    Ok(String::from_utf8(out.stdout)?.trim().to_owned())
}
