//! Version-aware config generators for the public networks.
//!
//! Companion to [`crate::regtest_conf`]: renders `zebrad.toml` for a validator booting from
//! a pre-synced chain archive (`regtest::archive_mount`).
//!
//! - Network = a *parameter*, not a second module: mainnet and testnet differ in two
//!   rendered values (`[network] network`, the per-network initial-peers key)
//! - [`ChainMotion`] is the whole axis: pinned = peerless + forced-finished + no peer-cache
//!   writes into the mount; following = zebra's stock `[network]` defaults, plus `[health]`
//! - No version gate fires yet; `_version` is plumbed for the first schema change

use crate::Network;
use crate::regtest_conf::Semver;

/// Panic guard: no coherent regtest render here (that has its own module)
fn assert_public(network: Network, who: &str) {
    assert!(
        network.is_public(),
        "{who} renders configs for the public networks; {} belongs to regtest_conf",
        network.as_str(),
    );
}

// ─────────────────────────────── zebrad ───────────────────────────────

/// Whether a restored node stays on its snapshot or syncs onward from it.
///
/// - `Following` names no peers: zebra ships the DNS seeders *as* `initial_<net>_peers`, so any
///   value here replaces discovery with that one list (tests hold the invariant)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChainMotion {
    Pinned,
    Following,
}

/// Outbound peers a following node aims for. Above zebra's default 25 because the compatible
/// share of the address space is small
const FOLLOWING_PEERSET_TARGET: u32 = 75;

/// Render a public-network `zebrad.toml`.
///
/// `cache_dir` = the container path the chain-archive PVC is mounted at. Only
/// `[state] cache_dir` points there (tests say why `[network] cache_dir` must not)
pub fn public_zebrad_conf(
    network: Network,
    motion: ChainMotion,
    _version: Semver,
    rpc_port: u16,
    cache_dir: &str,
    metrics_port: Option<u16>,
) -> String {
    assert_public(network, "public_zebrad_conf");
    let metrics_block = match metrics_port {
        Some(port) => format!("\n\n[metrics]\nendpoint_addr = \"0.0.0.0:{port}\""),
        None => String::new(),
    };
    let network_name = network.zebra_name();
    let peers_key = network.initial_peers_key();
    let (peering, finished_sync, peerset_target, health_block) = match motion {
        ChainMotion::Pinned => (
            format!(
                "\n# Peer cache, not the state cache (would write peer lists into the snapshot mount).\n\
                 cache_dir = false\n\
                 # Never: empty seeds stop the dial list, not the crawler.\n\
                 crawl_new_peer_interval = \"365d\"\n\
                 {peers_key} = []\n\
                 listen_addr = \"0.0.0.0:0\""
            ),
            "\n# The chain is complete at the pinned height.\ndebug_force_finished_sync = true",
            25,
            String::new(),
        ),
        // `{peers_key}` + `crawl_new_peer_interval` omitted → zebra's own defaults, which *are*
        // the ZIP-204 DNS seeders. Peer cache shares the chain volume (zebra's own layout:
        // `network/` beside `state/`), so a restart re-dials known-good peers instead of reseeding
        ChainMotion::Following => (
            format!(
                "\ncache_dir = \"{cache_dir}\"\nlisten_addr = \"0.0.0.0:{}\"",
                crate::ports::ZEBRAD_P2P
            ),
            "",
            FOLLOWING_PEERSET_TARGET,
            format!(
                "\n\n[health]\n\
                 listen_addr = \"0.0.0.0:{}\"\n\
                 enforce_on_test_networks = true\n\
                 min_connected_peers = 1\n\
                 ready_max_blocks_behind = 2",
                crate::ports::ZEBRAD_HEALTH
            ),
        ),
    };
    format!(
        "\
# Generated by `ztest::public_conf::public_zebrad_conf` — do not hand-edit.
# Single-node zebrad against a pre-synced chain snapshot mounted at
# `cache_dir`. Which snapshot is a property of the mount, not of this TOML.

[consensus]
checkpoint_sync = true{health_block}

[mempool]
eviction_memory_time = \"1h\"
tx_cost_limit = 80000000

[network]{peering}
network = \"{network_name}\"
peerset_initial_target_size = {peerset_target}

[rpc]{finished_sync}
enable_cookie_auth = false
parallel_cpu_threads = 0
listen_addr = \"0.0.0.0:{rpc_port}\"

[state]
cache_dir = \"{cache_dir}\"
delete_old_database = false
ephemeral = false

[sync]
checkpoint_verify_concurrency_limit = 1000
download_concurrency_limit = 50
full_verify_concurrency_limit = 20
parallel_cpu_threads = 0

[tracing]
buffer_limit = 128000
force_use_color = true
use_color = true
filter = \"info\"
use_journald = false{metrics_block}
"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v() -> Semver {
        "5.1.1".parse().unwrap()
    }

    const PUBLIC: [Network; 2] = [Network::Mainnet, Network::Testnet];

    /// `[state] cache_dir` = the chain DB; `[network] cache_dir` = the cached peer list,
    /// a different key with the same name. Both pointed at the mount had zebra rewriting
    /// `network/testnet.peers` inside the snapshot every 20 s
    #[test]
    fn only_the_state_cache_dir_points_at_the_snapshot() {
        for network in PUBLIC {
            let toml = public_zebrad_conf(
                network,
                ChainMotion::Pinned,
                v(),
                18232,
                "/var/cache/zebrad",
                None,
            );
            assert_eq!(toml.matches("cache_dir = \"/var/cache/zebrad\"").count(), 1);
            let state = toml.find("[state]").expect("[state] table");
            let mount = toml.find("cache_dir = \"/var/cache/zebrad\"").expect("state cache_dir");
            assert!(state < mount, "the snapshot mount must be [state]'s");
            assert!(toml.contains("cache_dir = false"), "peer cache disabled");
            assert!(toml.contains("listen_addr = \"0.0.0.0:18232\""));
        }
    }

    /// Pinned snapshot = frozen, so nothing may move it. Without these zebra crawls for
    /// peers forever, reports the pinned tip as ~99 % of an imagined mainnet-scale one,
    /// and sits one connection away from leaving the tip every probe assumes
    #[test]
    fn a_pinned_validator_does_not_chase_the_network() {
        for network in PUBLIC {
            let toml = public_zebrad_conf(
                network,
                ChainMotion::Pinned,
                v(),
                18232,
                "/var/cache/zebrad",
                None,
            );
            assert!(toml.contains("debug_force_finished_sync = true"));
            assert!(toml.contains("crawl_new_peer_interval = \"365d\""));
        }
    }

    /// Peers key is network-*specific by name* → `initial_testnet_peers = []` in a mainnet
    /// config silences the wrong list: mainnet seeds keep their defaults, the node dials
    /// out, and it syncs its tip off the pin the fixture depends on
    #[test]
    fn each_network_empties_its_own_peer_list() {
        let main = public_zebrad_conf(
            Network::Mainnet,
            ChainMotion::Pinned,
            v(),
            18232,
            "/var/cache/zebrad",
            None,
        );
        assert!(main.contains("network = \"Mainnet\""));
        assert!(main.contains("initial_mainnet_peers = []"));
        assert!(!main.contains("initial_testnet_peers"));

        let test = public_zebrad_conf(
            Network::Testnet,
            ChainMotion::Pinned,
            v(),
            18232,
            "/var/cache/zebrad",
            None,
        );
        assert!(test.contains("network = \"Testnet\""));
        assert!(test.contains("initial_testnet_peers = []"));
        assert!(!test.contains("initial_mainnet_peers"));
    }

    /// Loopback bind = unreachable from the test pod (reads as a dead component)
    #[test]
    fn no_listener_binds_to_loopback() {
        for network in PUBLIC {
            let conf = public_zebrad_conf(
                network,
                ChainMotion::Following,
                v(),
                18232,
                "/var/cache/zebrad",
                Some(9999),
            );
            for line in conf.lines().filter(|l| {
                !l.trim_start().starts_with('#')
                    && (l.contains("listen_addr") || l.contains("endpoint_addr"))
            }) {
                assert!(
                    line.contains(crate::ports::LISTEN_ALL),
                    "listener does not bind LISTEN_ALL and is unreachable across pods: {line}"
                );
            }
        }
    }

    #[test]
    #[should_panic(expected = "belongs to regtest_conf")]
    fn regtest_is_rejected_rather_than_rendered() {
        public_zebrad_conf(
            Network::Regtest,
            ChainMotion::Pinned,
            v(),
            18232,
            "/var/cache/zebrad",
            None,
        );
    }

    /// Following = zebra's own defaults: seeds dialled, crawler on, sync progress reported
    /// honestly (a forced-finished flag would claim the tip mid-catch-up)
    #[test]
    fn a_following_validator_dials_the_network_and_reports_real_progress() {
        for network in PUBLIC {
            let toml = public_zebrad_conf(
                network,
                ChainMotion::Following,
                v(),
                18232,
                "/var/cache/zebrad",
                None,
            );
            assert!(!toml.contains("crawl_new_peer_interval"));
            assert!(!toml.contains("debug_force_finished_sync"));
            assert!(toml.contains("peerset_initial_target_size = 75"));
        }
    }

    /// The shipped `initial_<net>_peers` ARE the DNS seeders, so naming even one address replaces
    /// discovery with that list. A following node must leave both keys unwritten.
    #[test]
    fn a_following_validator_names_no_initial_peers() {
        for network in PUBLIC {
            let toml = public_zebrad_conf(
                network,
                ChainMotion::Following,
                v(),
                18232,
                "/var/cache/zebrad",
                None,
            );
            assert!(!toml.contains("initial_mainnet_peers"), "{toml}");
            assert!(!toml.contains("initial_testnet_peers"), "{toml}");
        }
    }

    /// Peer cache shares the chain volume (zebra's own `network/` beside `state/`): a restart
    /// re-dials known-good peers instead of reseeding from DNS.
    #[test]
    fn a_following_validator_caches_its_peers_and_accepts_inbound() {
        let toml = public_zebrad_conf(
            Network::Mainnet,
            ChainMotion::Following,
            v(),
            18232,
            "/var/cache/zebrad",
            None,
        );
        assert_eq!(toml.matches("cache_dir = \"/var/cache/zebrad\"").count(), 2, "{toml}");
        assert!(toml.contains(&format!("listen_addr = \"0.0.0.0:{}\"", crate::ports::ZEBRAD_P2P)));
    }

    /// `/ready` is the only honest "at the network tip" oracle; zebra serves it only when a
    /// config names `health.listen_addr`, and a pinned node has no tip to be near.
    #[test]
    fn health_endpoints_serve_only_for_a_following_validator() {
        let following = public_zebrad_conf(
            Network::Mainnet,
            ChainMotion::Following,
            v(),
            18232,
            "/var/cache/zebrad",
            None,
        );
        assert!(
            following
                .contains(&format!("listen_addr = \"0.0.0.0:{}\"", crate::ports::ZEBRAD_HEALTH))
        );
        assert!(following.contains("enforce_on_test_networks = true"));

        let pinned = public_zebrad_conf(
            Network::Mainnet,
            ChainMotion::Pinned,
            v(),
            18232,
            "/var/cache/zebrad",
            None,
        );
        assert!(!pinned.contains("[health]"));
    }
}
