//! Version-aware config generators for the public networks.
//!
//! Companion to [`crate::regtest_conf`]. Renders `zebrad.toml` and
//! `zainod.toml` for a component booting from a pre-synced chain archive,
//! mounted via `regtest::archive_mount`.
//!
//! The network is a *parameter*, not a copy of the module. Mainnet and testnet
//! differ in exactly two rendered values — `[network] network` and the
//! per-network initial-peers key — while everything that makes a pinned
//! snapshot behave (peerless, forced-finished sync, no peer-cache writes into
//! the mount) is identical and stated once here. A second module would have
//! duplicated that contract and let the two copies drift.
//!
//! No version gates fire yet; `_version` is plumbed so a future schema change
//! is one predicate away.

use crate::ArchiveNetwork;
use crate::regtest_conf::Semver;

/// Panic guard for the generators below: neither renders a coherent config for
/// regtest, which has its own module.
fn assert_public(network: ArchiveNetwork, who: &str) {
    assert!(
        network.is_public(),
        "{who} renders configs for the public networks; {} belongs to regtest_conf",
        network.as_str(),
    );
}

// ─────────────────────────────── zebrad ───────────────────────────────

/// Render a public-network `zebrad.toml`.
///
/// `cache_dir` is the container path the chain-archive PVC is mounted at. Only
/// `[state] cache_dir` points at it; see the tests for why `[network]
/// cache_dir` must not.
pub fn public_zebrad_conf(
    network: ArchiveNetwork,
    _version: Semver,
    rpc_port: u16,
    cache_dir: &str,
    indexer_listen_port: Option<u16>,
    metrics_port: Option<u16>,
) -> String {
    assert_public(network, "public_zebrad_conf");
    let metrics_block = match metrics_port {
        Some(port) => format!("\n\n[metrics]\nendpoint_addr = \"0.0.0.0:{port}\""),
        None => String::new(),
    };
    // zebra starts its indexer gRPC server only when this key is present. Without
    // it a colocated zaino `Direct` backend has no address to dial and refuses to
    // construct at all ("Missing validator_grpc_listen_address"), which is why the
    // restored-chain topology could never start.
    let indexer_line = match indexer_listen_port {
        Some(port) => format!("\nindexer_listen_addr = \"0.0.0.0:{port}\""),
        None => String::new(),
    };
    let network_name = network.zebra_name();
    let peers_key = network.initial_peers_key();
    format!(
        "\
# Generated by `ztest::public_conf::public_zebrad_conf` — do not hand-edit.
# Single-node zebrad against a pre-synced chain snapshot mounted at
# `cache_dir`. Which snapshot is a property of the mount, not of this TOML.

[consensus]
checkpoint_sync = true

[mempool]
eviction_memory_time = \"1h\"
tx_cost_limit = 80000000

[network]
# Peer cache, not the state cache. Nothing to cache without seeds.
cache_dir = false
# Never: empty seeds stop the dial list, not the crawler.
crawl_new_peer_interval = \"365d\"
{peers_key} = []
listen_addr = \"0.0.0.0:0\"
network = \"{network_name}\"
peerset_initial_target_size = 25

[rpc]
# The chain is complete at the pinned height.
debug_force_finished_sync = true
enable_cookie_auth = false
parallel_cpu_threads = 0
listen_addr = \"0.0.0.0:{rpc_port}\"{indexer_line}

[state]
cache_dir = \"{cache_dir}\"
delete_old_database = false
ephemeral = false

[sync]
checkpoint_verify_concurrency_limit = 1000
download_concurrency_limit = 50
full_verify_concurrency_limit = 20
parallel_cpu_threads = 0

[tracing]
buffer_limit = 128000
force_use_color = true
use_color = true
filter = \"info\"
use_journald = false{metrics_block}
"
    )
}

// ─────────────────────────────── zainod ───────────────────────────────

/// Render `zainod.toml` for a public-network pod.
///
/// `backend` picks fetch vs. state; `validator_host` / `validator_rpc_port`
/// locate the paired zebrad pod; `zebra_db_path` / `zaino_db_path` are the
/// container-side mount paths.
#[allow(clippy::too_many_arguments)]
pub fn public_zainod_conf(
    network: ArchiveNetwork,
    _version: Semver,
    backend_literal: &str,
    grpc_listen_port: u16,
    jsonrpc_listen_port: u16,
    validator_host: &str,
    validator_rpc_port: u16,
    zebra_db_path: &str,
    zaino_db_path: &str,
    validator_grpc: Option<&str>,
    metrics_port: Option<u16>,
) -> String {
    assert_public(network, "public_zainod_conf");
    // Every listener binds `LISTEN_ALL`; see that constant for why loopback
    // cannot work under pod-per-test.
    let listen_all = crate::handles::ports::LISTEN_ALL;
    let metrics_line = match metrics_port {
        Some(port) => format!("\nmetrics_endpoint = '{listen_all}:{port}'"),
        None => String::new(),
    };
    // `backend = 'direct'` is rejected at config load without this key, so it is
    // required for the state backend and meaningless for fetch (which forwards
    // every query over JSON-RPC and never opens a DB).
    let validator_grpc_line = match validator_grpc {
        Some(addr) => format!("\nvalidator_grpc_listen_address = '{addr}'"),
        None => String::new(),
    };
    let network_name = network.zebra_name();
    format!(
        "\
# Generated by `ztest::public_conf::public_zainod_conf` — do not hand-edit.

backend = '{backend_literal}'
zebra_db_path = '{zebra_db_path}'
network = '{network_name}'{metrics_line}

[grpc_settings]
listen_address = '{listen_all}:{grpc_listen_port}'

[json_server_settings]
json_rpc_listen_address = '{listen_all}:{jsonrpc_listen_port}'

[validator_settings]
validator_jsonrpc_listen_address = '{validator_host}:{validator_rpc_port}'{validator_grpc_line}
validator_user = 'xxxxxx'
validator_password = 'xxxxxx'

[service]
timeout = 30
channel_size = 32

[storage.cache]
capacity = 10000
shard_power = 4

[storage.database]
path = '{zaino_db_path}'
size = 128
"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v() -> Semver {
        "5.1.1".parse().unwrap()
    }

    const PUBLIC: [ArchiveNetwork; 2] = [ArchiveNetwork::Mainnet, ArchiveNetwork::Testnet];

    /// Only `[state] cache_dir` is the chain DB. `[network] cache_dir` is the
    /// cached peer list — a different key with the same name. Pointing both at
    /// the mount had zebra rewriting `network/testnet.peers` inside the snapshot
    /// every 20 s.
    #[test]
    fn only_the_state_cache_dir_points_at_the_snapshot() {
        for network in PUBLIC {
            let toml = public_zebrad_conf(network, v(), 18232, "/var/cache/zebrad", None, None);
            assert_eq!(toml.matches("cache_dir = \"/var/cache/zebrad\"").count(), 1);
            let state = toml.find("[state]").expect("[state] table");
            let mount = toml
                .find("cache_dir = \"/var/cache/zebrad\"")
                .expect("state cache_dir");
            assert!(state < mount, "the snapshot mount must be [state]'s");
            assert!(toml.contains("cache_dir = false"), "peer cache disabled");
            assert!(toml.contains("listen_addr = \"0.0.0.0:18232\""));
        }
    }

    /// A pinned snapshot is frozen, so nothing may try to move it. Without these
    /// zebra crawls for peers forever and reports the pinned tip as ~99 % of an
    /// imagined mainnet-scale one — and a validator still hunting for peers is
    /// one connection away from leaving the tip every probe assumes it holds.
    #[test]
    fn a_pinned_validator_does_not_chase_the_network() {
        for network in PUBLIC {
            let toml = public_zebrad_conf(network, v(), 18232, "/var/cache/zebrad", None, None);
            assert!(toml.contains("debug_force_finished_sync = true"));
            assert!(toml.contains("crawl_new_peer_interval = \"365d\""));
        }
    }

    /// The peers key is network-*specific by name*. Emitting
    /// `initial_testnet_peers = []` into a mainnet config silences the wrong
    /// list: the mainnet seeds keep their defaults, the node dials out, and it
    /// syncs its tip off the pin the whole fixture depends on.
    #[test]
    fn each_network_empties_its_own_peer_list() {
        let main = public_zebrad_conf(
            ArchiveNetwork::Mainnet,
            v(),
            18232,
            "/var/cache/zebrad",
            None,
            None,
        );
        assert!(main.contains("network = \"Mainnet\""));
        assert!(main.contains("initial_mainnet_peers = []"));
        assert!(!main.contains("initial_testnet_peers"));

        let test = public_zebrad_conf(
            ArchiveNetwork::Testnet,
            v(),
            18232,
            "/var/cache/zebrad",
            None,
            None,
        );
        assert!(test.contains("network = \"Testnet\""));
        assert!(test.contains("initial_testnet_peers = []"));
        assert!(!test.contains("initial_mainnet_peers"));
    }

    /// The zainod generator names its network too, and must agree with the
    /// zebrad pod it is pointed at.
    #[test]
    fn zainod_names_the_same_network_as_zebrad() {
        for network in PUBLIC {
            let toml = public_zainod_conf(
                network,
                v(),
                "fetch",
                8137,
                8232,
                "zebrad",
                18232,
                "/db/zebra",
                "/db/zaino",
                None,
                None,
            );
            assert!(toml.contains(&format!("network = '{}'", network.zebra_name())));
        }
    }

    /// zebra starts its indexer gRPC only when the key is present. Its absence on
    /// the restored-chain path left `backend = 'direct'` unconfigurable, so the
    /// state indexer could not start at all.
    #[test]
    fn zebrad_indexer_listen_addr_is_gated_on_the_port() {
        let net = ArchiveNetwork::Testnet;
        let off = public_zebrad_conf(net, v(), 18232, "/var/cache/zebrad", None, None);
        let on = public_zebrad_conf(net, v(), 18232, "/var/cache/zebrad", Some(18230), None);
        assert!(!off.contains("indexer_listen_addr"));
        assert!(on.contains("indexer_listen_addr = \"0.0.0.0:18230\""));
        // Must land on `[rpc]`, beside `listen_addr`, not in the next table.
        let rpc = on.find("[rpc]").expect("[rpc] table");
        let state = on.find("[state]").expect("[state] table");
        let indexer = on.find("indexer_listen_addr").expect("indexer key");
        assert!(rpc < indexer && indexer < state);
    }

    /// The regression: the public zainod generator bound gRPC to `0.0.0.0` and
    /// JSON-RPC to `127.0.0.1`. gRPC worked, so the indexer looked alive and
    /// `env.build()` passed — while every JSON-RPC call from the test pod got
    /// `Connection refused`, which read as a dead indexer rather than a bind
    /// address. Checked across *both* generators, since one having the right
    /// address is exactly the state that hid this.
    #[test]
    fn no_generator_binds_a_listener_to_loopback() {
        let mut confs = vec![crate::regtest_conf::regtest_zainod_conf(
            v(),
            "fetch",
            8137,
            8232,
            "zebrad",
            28232,
            "/db/zebra",
            "/db/zaino",
            None,
            Some(9998),
        )];
        for network in PUBLIC {
            confs.push(public_zainod_conf(
                network,
                v(),
                "fetch",
                8137,
                8232,
                "zebrad",
                18232,
                "/db/zebra",
                "/db/zaino",
                None,
                Some(9998),
            ));
            confs.push(public_zebrad_conf(
                network,
                v(),
                18232,
                "/var/cache/zebrad",
                Some(18230),
                Some(9999),
            ));
        }
        for conf in confs {
            for line in conf.lines().filter(|l| {
                !l.trim_start().starts_with('#')
                    && (l.contains("listen_add") || l.contains("_endpoint"))
                    // `validator_*` names a peer to dial, not a socket to bind.
                    && !l.contains("validator_")
            }) {
                assert!(
                    line.contains(crate::handles::ports::LISTEN_ALL),
                    "listener does not bind LISTEN_ALL and is unreachable across pods: {line}"
                );
            }
        }
    }

    #[test]
    #[should_panic(expected = "belongs to regtest_conf")]
    fn regtest_is_rejected_rather_than_rendered() {
        public_zebrad_conf(
            ArchiveNetwork::Regtest,
            v(),
            18232,
            "/var/cache/zebrad",
            None,
            None,
        );
    }
}
