//! Version-aware testnet config generators.
//!
//! Companion to [`crate::regtest_conf`]. Renders `zebrad.toml` and
//! `zainod.toml` for the testnet network, paired with a pre-synced chain
//! archive mounted via [`crate::regtest::testnet_chain_archive`]. The
//! `variant` argument selects which archive, not which config.
//!
//! All testnet variants (`orchard`, `sapling`, ...) share the same TOML
//! body; they differ only in which chain snapshot is mounted at the pod's
//! cache path. The generator is parameterised by `version` plus path-only
//! knobs, with no per-variant branches.
//!
//! To add a release: extend the [`crate::regtest_conf::Semver`] capability
//! predicates (or add new ones) and switch on them in the generator. The
//! shared `Semver` / `versions` constants cover both networks.

use crate::regtest_conf::Semver;

/// Which zaino backend the rendered `zainod.toml` configures.
///
/// `Fetch` and `State` differ in one TOML line (`backend = ...`) but map
/// to distinct test invocations. Kept as an enum so the call site records
/// intent and a future per-backend schema split is one match arm away.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ZainodBackend {
    /// Pull blocks through the validator's JSON-RPC. Pairs with
    /// `Indexer::testnet(variant)`.
    Fetch,
    /// Read the validator's on-disk state directory directly. Pairs
    /// with `Indexer::testnet_state(variant)`.
    State,
}

impl ZainodBackend {
    /// The literal that lands in `backend = '…'` inside `zainod.toml`.
    fn as_toml(self) -> &'static str {
        match self {
            ZainodBackend::Fetch => "fetch",
            ZainodBackend::State => "state",
        }
    }
}

// ─────────────────────────────── zebrad ───────────────────────────────

/// Render the testnet `zebrad.toml`.
///
/// `rpc_port` is the JSON-RPC listen port (testnet canonical: 18232).
/// `cache_dir` is the container path the chain-archive PVC is mounted at;
/// both `[network] cache_dir` and `[state] cache_dir` point at it so
/// zebrad reads the pre-synced snapshot and writes back into the same
/// volume. The path is the generator's knob, not the snapshot's; variant
/// selection happens at the mount layer.
///
/// No version gates fire yet: the testnet TOML schema is stable across the
/// zebrad releases we exercise. The `_version` parameter is plumbed
/// through so a future schema change is one predicate away.
pub fn testnet_zebrad_conf(_version: Semver, rpc_port: u16, cache_dir: &str) -> String {
    format!(
        "\
# Generated by `ztest::testnet_conf::testnet_zebrad_conf` — do not hand-edit.
# Testnet fixture: single-node zebrad against a pre-synced chain
# snapshot mounted at `cache_dir`. Variant selection (orchard, sapling, …)
# happens at the chain-archive mount, not in this TOML.

[consensus]
checkpoint_sync = true

[mempool]
eviction_memory_time = \"1h\"
tx_cost_limit = 80000000

[network]
cache_dir = \"{cache_dir}\"
initial_testnet_peers = []
listen_addr = \"0.0.0.0:0\"
network = \"Testnet\"
peerset_initial_target_size = 25

[rpc]
debug_force_finished_sync = false
enable_cookie_auth = false
parallel_cpu_threads = 0
listen_addr = \"0.0.0.0:{rpc_port}\"

[state]
cache_dir = \"{cache_dir}\"
delete_old_database = false
ephemeral = false

[sync]
checkpoint_verify_concurrency_limit = 1000
download_concurrency_limit = 50
full_verify_concurrency_limit = 20
parallel_cpu_threads = 0

[tracing]
buffer_limit = 128000
force_use_color = false
use_color = true
filter = \"info\"
use_journald = false
"
    )
}

// ─────────────────────────────── zainod ───────────────────────────────

/// Render `zainod.toml` for a testnet pod.
///
/// `backend` picks fetch vs. state (a single-line difference in the TOML,
/// kept typed so the call site records intent). `grpc_listen_port` and
/// `jsonrpc_listen_port` are zainod's own listeners; `validator_host` is
/// the in-cluster DNS name of the paired zebrad pod and
/// `validator_rpc_port` its JSON-RPC port. `zebra_db_path` and
/// `zaino_db_path` are container-side paths the snapshot/scratch mounts
/// land at.
#[allow(clippy::too_many_arguments)]
pub fn testnet_zainod_conf(
    _version: Semver,
    backend: ZainodBackend,
    grpc_listen_port: u16,
    jsonrpc_listen_port: u16,
    validator_host: &str,
    validator_rpc_port: u16,
    zebra_db_path: &str,
    zaino_db_path: &str,
) -> String {
    let backend_literal = backend.as_toml();
    format!(
        "\
# Generated by `ztest::testnet_conf::testnet_zainod_conf` — do not hand-edit.

backend = '{backend_literal}'
zebra_db_path = '{zebra_db_path}'
network = 'Testnet'

[grpc_settings]
listen_address = '0.0.0.0:{grpc_listen_port}'

[json_server_settings]
json_rpc_listen_address = '127.0.0.1:{jsonrpc_listen_port}'

[validator_settings]
validator_jsonrpc_listen_address = '{validator_host}:{validator_rpc_port}'
validator_user = 'xxxxxx'
validator_password = 'xxxxxx'

[service]
timeout = 30
channel_size = 32

[storage.cache]
capacity = 10000
shard_power = 4

[storage.database]
path = '{zaino_db_path}'
size = 128
"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v() -> Semver {
        "5.1.1".parse().unwrap()
    }

    #[test]
    fn zebrad_renders_with_cache_dir_in_both_state_and_network() {
        let toml = testnet_zebrad_conf(v(), 18232, "/var/cache/zebrad");
        // Both [network] and [state] must point at the snapshot mount, or
        // zebrad re-syncs from genesis and ignores the archive.
        assert_eq!(toml.matches("cache_dir = \"/var/cache/zebrad\"").count(), 2);
        assert!(toml.contains("listen_addr = \"0.0.0.0:18232\""));
        assert!(toml.contains("network = \"Testnet\""));
    }

    #[test]
    fn zainod_fetch_vs_state_differ_only_in_backend_line() {
        let v = v();
        let fetch = testnet_zainod_conf(
            v,
            ZainodBackend::Fetch,
            8137,
            8232,
            "zebrad",
            18232,
            "/var/lib/zaino/zebra-db",
            "/var/lib/zaino/db",
        );
        let state = testnet_zainod_conf(
            v,
            ZainodBackend::State,
            8137,
            8232,
            "zebrad",
            18232,
            "/var/lib/zaino/zebra-db",
            "/var/lib/zaino/db",
        );
        assert!(fetch.contains("backend = 'fetch'"));
        assert!(state.contains("backend = 'state'"));
        // Everything else must match: the two are sibling TOMLs.
        assert_eq!(
            fetch.replace("backend = 'fetch'", ""),
            state.replace("backend = 'state'", "")
        );
    }
}
