//! Version-aware testnet config generators.
//!
//! Companion to [`crate::regtest_conf`]. Renders `zebrad.toml` and
//! `zainod.toml` for the testnet network, paired with a pre-synced chain
//! archive mounted via [`crate::regtest::testnet_chain_archive`]. All
//! variants (`orchard`, `sapling`, ...) share the same TOML body; the
//! `variant` selects only which chain snapshot is mounted.

use crate::regtest_conf::Semver;

// ─────────────────────────────── zebrad ───────────────────────────────

/// Render the testnet `zebrad.toml`.
///
/// `cache_dir` is the container path the chain-archive PVC is mounted at;
/// both `[network]` and `[state]` point at it so zebrad reads the
/// pre-synced snapshot and writes back into the same volume.
///
/// No version gates fire yet; `_version` is plumbed so a future schema
/// change is one predicate away.
pub fn testnet_zebrad_conf(
    _version: Semver,
    rpc_port: u16,
    cache_dir: &str,
    metrics_port: Option<u16>,
) -> String {
    let metrics_block = match metrics_port {
        Some(port) => format!("\n\n[metrics]\nendpoint_addr = \"0.0.0.0:{port}\""),
        None => String::new(),
    };
    format!(
        "\
# Generated by `ztest::testnet_conf::testnet_zebrad_conf` — do not hand-edit.
# Testnet fixture: single-node zebrad against a pre-synced chain
# snapshot mounted at `cache_dir`. Variant selection (orchard, sapling, …)
# happens at the chain-archive mount, not in this TOML.

[consensus]
checkpoint_sync = true

[mempool]
eviction_memory_time = \"1h\"
tx_cost_limit = 80000000

[network]
cache_dir = \"{cache_dir}\"
initial_testnet_peers = []
listen_addr = \"0.0.0.0:0\"
network = \"Testnet\"
peerset_initial_target_size = 25

[rpc]
debug_force_finished_sync = false
enable_cookie_auth = false
parallel_cpu_threads = 0
listen_addr = \"0.0.0.0:{rpc_port}\"

[state]
cache_dir = \"{cache_dir}\"
delete_old_database = false
ephemeral = false

[sync]
checkpoint_verify_concurrency_limit = 1000
download_concurrency_limit = 50
full_verify_concurrency_limit = 20
parallel_cpu_threads = 0

[tracing]
buffer_limit = 128000
force_use_color = true
use_color = true
filter = \"info\"
use_journald = false{metrics_block}
"
    )
}

// ─────────────────────────────── zainod ───────────────────────────────

/// Render `zainod.toml` for a testnet pod.
///
/// `backend` picks fetch vs. state; `validator_host` / `validator_rpc_port`
/// locate the paired zebrad pod; `zebra_db_path` / `zaino_db_path` are the
/// container-side mount paths.
#[allow(clippy::too_many_arguments)]
pub fn testnet_zainod_conf(
    _version: Semver,
    backend_literal: &str,
    grpc_listen_port: u16,
    jsonrpc_listen_port: u16,
    validator_host: &str,
    validator_rpc_port: u16,
    zebra_db_path: &str,
    zaino_db_path: &str,
    metrics_port: Option<u16>,
) -> String {
    let metrics_line = match metrics_port {
        Some(port) => format!("\nmetrics_endpoint = '0.0.0.0:{port}'"),
        None => String::new(),
    };
    format!(
        "\
# Generated by `ztest::testnet_conf::testnet_zainod_conf` — do not hand-edit.

backend = '{backend_literal}'
zebra_db_path = '{zebra_db_path}'
network = 'Testnet'{metrics_line}

[grpc_settings]
listen_address = '0.0.0.0:{grpc_listen_port}'

[json_server_settings]
json_rpc_listen_address = '127.0.0.1:{jsonrpc_listen_port}'

[validator_settings]
validator_jsonrpc_listen_address = '{validator_host}:{validator_rpc_port}'
validator_user = 'xxxxxx'
validator_password = 'xxxxxx'

[service]
timeout = 30
channel_size = 32

[storage.cache]
capacity = 10000
shard_power = 4

[storage.database]
path = '{zaino_db_path}'
size = 128
"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v() -> Semver {
        "5.1.1".parse().unwrap()
    }

    #[test]
    fn zebrad_renders_with_cache_dir_in_both_state_and_network() {
        let toml = testnet_zebrad_conf(v(), 18232, "/var/cache/zebrad", None);
        // Both [network] and [state] must point at the snapshot mount, or
        // zebrad re-syncs from genesis and ignores the archive.
        assert_eq!(toml.matches("cache_dir = \"/var/cache/zebrad\"").count(), 2);
        assert!(toml.contains("listen_addr = \"0.0.0.0:18232\""));
        assert!(toml.contains("network = \"Testnet\""));
    }

    #[test]
    fn zainod_fetch_vs_state_differ_only_in_backend_line() {
        let v = v();
        let fetch = testnet_zainod_conf(
            v,
            "fetch",
            8137,
            8232,
            "zebrad",
            18232,
            "/var/lib/zaino/zebra-db",
            "/var/lib/zaino/db",
            None,
        );
        let state = testnet_zainod_conf(
            v,
            "state",
            8137,
            8232,
            "zebrad",
            18232,
            "/var/lib/zaino/zebra-db",
            "/var/lib/zaino/db",
            None,
        );
        assert!(fetch.contains("backend = 'fetch'"));
        assert!(state.contains("backend = 'state'"));
        // Everything else must match: the two are sibling TOMLs.
        assert_eq!(
            fetch.replace("backend = 'fetch'", ""),
            state.replace("backend = 'state'", "")
        );
    }

    #[test]
    fn testnet_metrics_stanzas_are_gated_on_metrics_port() {
        let zeb_off = testnet_zebrad_conf(v(), 18232, "/var/cache/zebrad", None);
        let zeb_on = testnet_zebrad_conf(v(), 18232, "/var/cache/zebrad", Some(9999));
        assert!(!zeb_off.contains("[metrics]"));
        assert!(zeb_on.contains("[metrics]"));
        assert!(zeb_on.contains("endpoint_addr = \"0.0.0.0:9999\""));

        let zai = |metrics_port| {
            testnet_zainod_conf(
                v(),
                "fetch",
                8137,
                8232,
                "zebrad",
                18232,
                "/var/lib/zaino/zebra-db",
                "/var/lib/zaino/db",
                metrics_port,
            )
        };
        assert!(!zai(None).contains("metrics_endpoint"));
        let zai_on = zai(Some(9998));
        assert!(zai_on.contains("metrics_endpoint = '0.0.0.0:9998'"));
        assert!(zai_on.find("metrics_endpoint").unwrap() < zai_on.find("[grpc_settings]").unwrap());
    }
}
